version: '3.8'

services:
  db:
    container_name: task_db
    image: postgres:17-alpine
    networks:
      - task_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    container_name: task_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - task_network
    volumes:
      - ./backend:/app
      - ./.docker/backend:/app/.docker/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_NAME=task_manager
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DJANGO_SUPERUSER_USERNAME=Sond
      - DJANGO_SUPERUSER_EMAIL=joaovictorbrtor2@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    command: sh -c "chmod +x /app/.docker/backend/entrypoint.sh && /app/.docker/backend/entrypoint.sh"

  frontend:
    container_name: task_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - task_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api

networks:
  task_network:
    driver: bridge

volumes:
  postgres_data:
