version: '3.8'

services:
  db:
    container_name: task_db
    image: postgres:17-alpine
    networks:
      - task_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    container_name: task_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - task_network
    volumes:
      - ./backend:/app
      - ./.docker/backend:/app/.docker/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=taskdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    command: [ "/app/.docker/backend/wait-for-it.sh" ]

  frontend:
    container_name: task_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - task_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api

networks:
  task_network:
    driver: bridge

volumes:
  postgres_data:
