# Generated by Django 5.1.3 on 2024-11-12 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='task_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])], verbose_name='Anexos'),
        ),
    ]
